### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\ "u279c'"

### ISSUE THREAD

**Issue by majidzamanian** [mimseyedi/Bernard#3]
during installation with Bernard_installation.py file we get error of UnicodeEncodeError: 'charmap' codec can't encode character '\ "u279c'"

to make it work we must edit line 77 and add jason library to the py file.
the edited line is like this:
bernard_file.write(json.dumps(request_to_repo.text, ensure_ascii = True))
insted of 
bernard_file.write(request_to_repo.text)

**Comment by mimseyedi** [comment]
The problem was solved and the Bernard installation file was modified.
Explanation of the problem: This problem occurs in the Windows operating system due to the lack of support for some encoders!
It is enough to set the encoder to utf-8 in line 76 when Bernard's file is to be downloaded and saved. In this way, the file is saved by a standard encoder.

with open("Bernard.py", "w", encoding="utf-8") as bernard_file:
        bernard_file.write(request_to_repo.text)

Thank you for your participation.
